---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python --version
      - pip --version
      - echo "Installing HashiCorp Packer..."
      - cd /usr/local/bin/ 
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && unzip packer.zip
      - unzip packer.zip
      - ./packer version
      - echo "Installing jq..."
      - echo "Validating centos7-golden.json"
      - ./packer validate amipipeline/centos7/centos7-golden.json
  build:
    commands:
      ### HashiCorp Packer cannot currently obtain the AWS CodeBuild-assigned role and its credentials
      ### Manually capture and configure the AWS CLI to provide HashiCorp Packer with AWS credentials
      ### More info here: https://github.com/mitchellh/packer/issues/4279
      - echo "Building HashiCorp Packer template, centos7-golden.json"
      - packer build -color=false ./amipipeline/centos7/centos7-golden.json | tee build.log
  post_build:
    commands:
      - echo "HashiCorp Packer build completed on `date`"